site_name: To Do List - V360

copyright: "Copyright &copy; 2024"

theme:
  name: material
  language: "pt"
  palette:
    primary: '#592a9e'
    accent: '#FF5C13'
# features:
#     - navigation.tabs
  font:
    text: "Open Sans"
    code: "sans-serif"
  # logo: assets/leafFavcon.svg
  # favicon: assets/leafFavcon.svg

nav:
  - Home: index.md
  - Brainstorm: brainstorm.md
  - Backlog: backlog.md
  - Arquitetura: arquitetura.md
